default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tinypress_development
  host: localhost

test:
  <<: *default
  database: tinypress_test
  host: localhost

production:
  <<: *default
  database: tinypress_production
  username: tinypress
  password: <%= ENV['tinypress_DATABASE_PASSWORD'] %>


